name: Node.js CI

on: 
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: sudo mkdir -p /var/svn
    - run: npm install
    - run: npx jest